ALTER TABLE "Purchase" ADD COLUMN "taxMode" TEXT NOT NULL DEFAULT 'NET';
ALTER TABLE "Purchase" ADD COLUMN "taxRate" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Purchase" ADD COLUMN "taxAmount" INTEGER NOT NULL DEFAULT 0;
